CREATE SCHEMA IF NOT EXISTS AUCTION_TRACKER;

SET SCHEMA AUCTION_TRACKER;

/************************************************/
/* ITEM  */
/************************************************/

CREATE TABLE AUCTION_TRACKER.ITEM (
	ID NUMERIC NOT NULL,
	CODE VARCHAR(10) NOT NULL,
	DESCRIPTION varchar(100) NOT NULL
);

ALTER TABLE AUCTION_TRACKER.ITEM ADD CONSTRAINT ITEM_PK PRIMARY KEY (ID);

CREATE SEQUENCE AUCTION_TRACKER.ITEM_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;

INSERT INTO AUCTION_TRACKER.ITEM (ID, CODE, DESCRIPTION) VALUES (AUCTION_TRACKER.ITEM_ID_SEQ.nextval,'CODE-1', 'Awesome item1');
INSERT INTO AUCTION_TRACKER.ITEM (ID, CODE, DESCRIPTION) VALUES (AUCTION_TRACKER.ITEM_ID_SEQ.nextval,'CODE-2', 'Awesome item2');
INSERT INTO AUCTION_TRACKER.ITEM (ID, CODE, DESCRIPTION) VALUES (AUCTION_TRACKER.ITEM_ID_SEQ.nextval,'CODE-3', 'Awesome item3');
/************************************************/
/* USER  */
/************************************************/

CREATE TABLE AUCTION_TRACKER.USER (
    ID   NUMBER      NOT NULL,
    USERNAME VARCHAR(50) NOT NULL
);

ALTER TABLE AUCTION_TRACKER.USER ADD CONSTRAINT USER_TYPE_PK PRIMARY KEY (ID);

INSERT INTO AUCTION_TRACKER.USER (ID, USERNAME) VALUES (1, 'neelam');
INSERT INTO AUCTION_TRACKER.USER (ID, USERNAME) VALUES (2, 'mehta');

/************************************************/
/* BB_ACCESS_DEVICE  */
/************************************************/

CREATE TABLE AUCTION_TRACKER.BID (
  ID              NUMBER        NOT NULL,
  ITEM_ID         NUMBER        NOT NULL,
  USER_ID         NUMBER        NOT NULL,
  AMOUNT          DECIMAL(10,2) NOT NULL
);

ALTER TABLE AUCTION_TRACKER.BID ADD CONSTRAINT BID_PK PRIMARY KEY (ID);

ALTER TABLE AUCTION_TRACKER.BID ADD CONSTRAINT BID_FK1 FOREIGN KEY (ITEM_ID) REFERENCES AUCTION_TRACKER.ITEM(ID);
ALTER TABLE AUCTION_TRACKER.BID ADD CONSTRAINT BID_FK2 FOREIGN KEY (USER_ID) REFERENCES AUCTION_TRACKER.USER(ID);

CREATE SEQUENCE AUCTION_TRACKER.BID_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;

INSERT INTO AUCTION_TRACKER.BID (ID, ITEM_ID, USER_ID,AMOUNT)
    VALUES (AUCTION_TRACKER.BID_ID_SEQ.nextval, (SELECT ID FROM AUCTION_TRACKER.ITEM WHERE CODE = 'CODE-1'),  (SELECT ID FROM AUCTION_TRACKER.USER WHERE USERNAME = 'neelam'), 3.50);

INSERT INTO AUCTION_TRACKER.BID (ID, ITEM_ID, USER_ID,AMOUNT)
    VALUES (AUCTION_TRACKER.BID_ID_SEQ.nextval, (SELECT ID FROM AUCTION_TRACKER.ITEM WHERE CODE = 'CODE-2'),  (SELECT ID FROM AUCTION_TRACKER.USER WHERE USERNAME = 'mehta'), 4.00);
